### ISSUE TITLE
Do you know how to implement any algorithm in Python?

### ISSUE THREAD

**Issue by abranhe** [AllAlgorithms/python#2]
<p align="center">
  <img src="https://cdn.abraham.gq/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available, or in [Python](https://github.com/AllAlgorithms/python) this case

**Comment by pablotrinidad** [comment]
Would you open this issue with the `Hacktoberfest` label for the haskell repo please? <3

**Comment by abranhe** [comment]
Sure @pablotrinidad!!!!!!!

**Comment by altaf933** [comment]
#49

**Comment by mrvnmchm** [comment]
Added Zeller's congruence algorithm via #50
