### ISSUE TITLE
Do you know any algorithm in Python?

### ISSUE THREAD

**Issue by abrahamcalf** [AllAlgorithms/python#67]
<p align="center">
  <img src="https://cdn.abranhe.com/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available, or in [Python](https://github.com/AllAlgorithms/python) this case

**Comment by hoseinfzad** [comment]
hi @abranhe i have some data-structure i would be happy to add to the project

**Comment by hinevics** [comment]
@abranhe can i add Levenshtein distance?

**Comment by RadientBrain** [comment]
Hi @abranhe I want to add Graham Scan algorithm. Can I make the PR ?

**Comment by abranhe** [comment]
> Hi @abranhe I want to add Graham Scan algorithm. Can I make the PR ?
> 
> 

Yes that would be awesome!!!

**Comment by RadientBrain** [comment]
Ok, I have made the *pull request*, my **pull request number is #95**. You can check it and merge it.

**Comment by abranhe** [comment]
@RadientBrain 

> Ok, I have made the _pull request_, my **pull request number is #95**. You can check it and merge it.
> Also, I suggest that you create a **new issue** for the editing the hyperlinks in the **README.md** file.
> As most of the hyperlinks are giving **404 Page not Found** _Error_.

Thanks, I have already created an issue to tackle this issue, here is the link if you want to contribute:

https://github.com/AllAlgorithms/algorithms/issues/42

**Comment by RadientBrain** [comment]
> @RadientBrain
> 
> > Ok, I have made the _pull request_, my **pull request number is #95**. You can check it and merge it.
> > Also, I suggest that you create a **new issue** for the editing the hyperlinks in the **README.md** file.
> > As most of the hyperlinks are giving **404 Page not Found** _Error_.
> 
> Thanks, I have already created an issue to tackle this issue, here is the link if you want to contribute:
> 
> [AllAlgorithms/algorithms#42](https://github.com/AllAlgorithms/algorithms/issues/42)

@abranhe, Thanks for considering my thoughts. Also, I would be happy to contribute but I think it would be good if other people also contribute as they will get a chance to contribute to this repo.

**Comment by thegeek13242** [comment]
@abranhe I have an implementation of a variant of the queue, which is implemented in C language. Can I rewrite the code & contribute to this repo?

**Comment by AyushSinha29** [comment]
hi @abrahamcalf can I add djikstra's algorithm?
